import { useEffect, useMemo, useRef, useState } from 'react'
import { changeLabel, compactValue, downloadJson, evaluateRules, formatValue, listSnapshots, loadRules, loadSnapshot, removeSnapshot, saveRules, storeSnapshot, validateRules, type InventoryResource, type InventorySnapshot, type SnapshotIndex } from '../lib/inventory'
import './inventory.css'
import { InventoryRules } from '../components/InventoryConfig'

const n = (value: number) => value.toLocaleString('ko-KR')
const date = (value: string) => new Date(value).toLocaleString('ko-KR', { timeZone:'Asia/Seoul', year:'numeric', month:'2-digit', day:'2-digit', hour:'2-digit', minute:'2-digit' })
const good = new Set(['SUCCESS','EMPTY','CACHED','NOT_APPLICABLE'])
type Tab = 'resources' | 'changes' | 'findings' | 'coverage'

export default function InventoryPage() {
  const [index,setIndex] = useState<SnapshotIndex[]>([])
  const [selected,setSelected] = useState('')
  const [snapshot,setSnapshot] = useState<InventorySnapshot>()
  const [tab,setTab] = useState<Tab>('resources')
  const [query,setQuery] = useState(''); const [compartment,setCompartment] = useState(''); const [region,setRegion] = useState(''); const [type,setType] = useState(''); const [service,setService] = useState('')
  const [detail,setDetail] = useState<InventoryResource>(); const [ids,setIds] = useState(() => localStorage.getItem('inventory-show-ids')==='yes'); const [page,setPage] = useState(0)
  const [error,setError] = useState(''); const [message,setMessage] = useState(''); const [busy,setBusy] = useState(false)
  const [importOpen,setImportOpen] = useState(false); const [jsonText,setJsonText] = useState(''); const [rulesText,setRulesText] = useState(''); const [rulesOpen,setRulesOpen] = useState(false)
  const [bridgeToken,setBridgeToken] = useState(''); const [bridgeFiles,setBridgeFiles] = useState<{ id:string; name:string; tenancy:string; at:string }[]>([])
  const [coverageLimit,setCoverageLimit] = useState(100); const [onlyIssues,setOnlyIssues] = useState(true)
  const [customRules,setCustomRules] = useState<Awaited<ReturnType<typeof loadRules>>>()
  const file = useRef<HTMLInputElement>(null)
  const refresh = async () => { const rows=await listSnapshots(); setIndex(rows); return rows }
  useEffect(() => { let active=true; Promise.all([listSnapshots(),loadRules()]).then(([rows,rules]) => { if (!active) return; setIndex(rows); setCustomRules(rules); setSelected(rows[0]?.id ?? '') }).catch(e => { if(active) setError(String(e)) }); return () => { active=false } },[])
  useEffect(() => { let active=true; if (!selected) return; loadSnapshot(selected).then(s => { if(active) { setSnapshot(s); setDetail(undefined); setCompartment(''); setRegion(''); setType(''); setService(''); setPage(0) } }).catch(e => { if(active) setError(String(e)) }); return () => { active=false } },[selected])
  useEffect(()=>{localStorage.setItem('inventory-show-ids',ids?'yes':'no')},[ids])
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setDetail(undefined);setImportOpen(false);setRulesOpen(false)}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[])
  const rules=useMemo(()=>customRules ?? snapshot?.rules ?? [],[customRules,snapshot])
  const findings=useMemo(() => snapshot ? evaluateRules(snapshot.resources,rules) : [],[snapshot,rules])
  const filtered=useMemo(() => (snapshot?.resources ?? []).filter(r => (!compartment || r.compartment===compartment) && (!region || r.region===region) && (!service || r.service===service) && (!type || r.type===type) && (!query || [r.name,r.type,r.ocid,r.compartment,JSON.stringify(r.properties),JSON.stringify(r.raw.defined_tags),JSON.stringify(r.raw.freeform_tags)].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()))).sort((a,b) => a.compartment.localeCompare(b.compartment) || a.region.localeCompare(b.region) || a.type.localeCompare(b.type) || a.name.localeCompare(b.name)),[snapshot,compartment,region,service,type,query])
  const keys=useMemo(() => new Set(filtered.map(r=>r.key)),[filtered])
  const displayed=filtered.slice(page*50,(page+1)*50)
  const groups=new Map<string,InventoryResource[]>()
  for (const r of displayed) groups.set(r.compartment,[...(groups.get(r.compartment)??[]),r])
  const tenants=[...new Map(index.map(i=>[i.tenancyId,i.tenancy])).entries()].sort((a,b)=>a[1].localeCompare(b[1]))
  const options=(field:'compartment'|'region'|'type') => [...new Set((snapshot?.resources ?? []).filter(r=>!service || r.service===service).map(r=>r[field]))].sort()
  const fields=type ? [...new Map(filtered.flatMap(r=>r.properties).map(p=>[p.field,p.label])).entries()].slice(0,8) : []
  const coverageIssues=(snapshot?.coverage ?? []).filter(c=>!good.has(c.status))
  const coverageRows=useMemo(()=>(snapshot?.coverage??[]).filter(c=>(!onlyIssues||!good.has(c.status))&&(!region||c.region===region)&&(!query||[c.operation,c.status,c.error,c.scope].join(' ').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>Number(good.has(a.status))-Number(good.has(b.status))),[snapshot,onlyIssues,region,query])
  async function importValue(value: unknown) { const id=await storeSnapshot(value); await refresh(); setSelected(id); setImportOpen(false); setJsonText(''); setMessage('이 브라우저에 저장했습니다. 파일 원본은 계속 보관하세요.') }
  async function perform(work:()=>Promise<void>) { setBusy(true); setError(''); setMessage(''); try { await work() } catch(e) { setError(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  async function importFiles(files: FileList | null) {
    if(!files?.length) return
    await perform(async()=>{ for(const f of Array.from(files)) { if(f.size>200*1024*1024) throw Error('파일 하나는 200MB 이하로 나누어주세요.'); await importValue(JSON.parse(await f.text())) } })
    if(file.current) file.current.value=''
  }
  const navigateResource=(key:string) => { const r=snapshot?.resources.find(r=>r.key===key) ?? snapshot?.resources.find(r=>r.ocid===key&&!r.type.includes('Attachment')) ?? snapshot?.resources.find(r=>r.ocid===key); if(r) setDetail(r); else setMessage('현재 스냅샷에 연결 대상의 세부 정보가 없습니다.') }
  const selectFilter=(setter:(v:string)=>void,value:string) => { setter(value); setPage(0) }
  return <section className="inventory" aria-label="리소스 현행화">
    <div className="inv-heading"><div><div className="inv-eyebrow">OCI INVENTORY</div><h1>리소스 현행화</h1><p>고객의 구성과 변화를 한곳에서 확인합니다.</p></div><div className="inv-actions"><button onClick={()=>{setRulesText(JSON.stringify(rules,null,2));setRulesOpen(true)}} disabled={!snapshot}>기준 관리</button><button className="inv-primary" onClick={()=>setImportOpen(true)}>JSON 가져오기</button></div></div>
    {error && <div className="inv-alert error" role="alert">{error}</div>}{message && <div className="inv-alert" role="status">{message}</div>}
    {!index.length ? <div className="inv-empty"><div className="inv-empty-icon">◫</div><h2>첫 번째 수집 파일을 열어보세요</h2><p>고객별 JSON을 가져오면 구성, 변경 이력, 핵심 설정을 탐색할 수 있습니다.<br/>데이터는 현재 브라우저에만 저장됩니다.</p><button className="inv-primary" onClick={()=>file.current?.click()}>수집 JSON 선택</button><div className="inv-empty-steps"><span>01 · Python으로 수집</span><span>02 · JSON 가져오기</span><span>03 · 구성과 변화 확인</span></div></div> : <div className="inv-workspace">
      <aside className="inv-customers"><div className="inv-side-title">테넌시 <span>{tenants.length}</span></div>{tenants.map(([id,name])=><button key={id} className={snapshot?.tenancy.id===id?'selected':''} onClick={()=>setSelected(index.find(i=>i.tenancyId===id)!.id)}><span className="inv-customer-mark">{name.slice(0,1).toUpperCase()}</span><span>{name}<small>{index.filter(i=>i.tenancyId===id).length}개 수집 이력</small></span></button>)}<p className="inv-local-note">브라우저에 가져온 고객만 표시됩니다.</p></aside>
      <main className="inv-main">{snapshot && <>
        <div className="inv-context"><div><h2>{snapshot.tenancy.name} <span>테넌시</span></h2><p>{snapshot.profile} · {snapshot.regions.join(', ')}</p></div><label>수집 시점<select aria-label="수집 시점" value={selected} onChange={e=>setSelected(e.target.value)}>{index.filter(i=>i.tenancyId===snapshot.tenancy.id).map(i=><option key={i.id} value={i.id}>{date(i.at)} · {n(i.count)}개</option>)}</select></label></div>
        <div className="inv-stats">{[['자원',snapshot.summary.resources],['변경',snapshot.changes.length],['설정 확인',findings.length],['수집 확인',coverageIssues.length]].map(([label,value],i)=><button key={label} className={i===3 && Number(value)>0?'attention':''} onClick={()=>setTab((['resources','changes','findings','coverage'] as Tab[])[i])}><span>{label}</span><strong>{n(Number(value))}</strong><small>{['현재 '+n(snapshot.summary.current)+' · 이전 정보 '+n(snapshot.summary.stale),snapshot.comparison_run_id?'이전 수집과 비교':'첫 수집 · 비교 기준 없음','기본값 차이와 설계 특성','실패·미지원 범위'][i]}</small></button>)}</div>
        {(snapshot.status!=='COMPLETE_REGISTERED_SCOPE' || coverageIssues.length>0) && <div className="inv-alert"><strong>일부 범위를 확인해야 합니다.</strong> 권한 부족·미지원·목록만 확인된 자원이 포함될 수 있습니다. <button onClick={()=>setTab('coverage')}>수집 범위 보기</button></div>}
        <div className="inv-tabs" role="tablist">{([['resources','자원 탐색'],['changes','변경 이력'],['findings','설정 확인'],['coverage','수집 범위']] as const).map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
        <div className="inv-filters"><input aria-label="자원 검색" placeholder={tab==='coverage'?'조회 작업, 상태, 오류 검색':'이름, IP, OCID, 태그 검색'} value={query} onChange={e=>selectFilter(setQuery,e.target.value)}/>{tab!=='coverage'&&<select aria-label="컴파트먼트" value={compartment} onChange={e=>selectFilter(setCompartment,e.target.value)}><option value="">전체 컴파트먼트</option>{options('compartment').map(v=><option key={v}>{v}</option>)}</select>}<select aria-label="리전" value={region} onChange={e=>selectFilter(setRegion,e.target.value)}><option value="">전체 리전</option>{options('region').map(v=><option key={v}>{v}</option>)}</select>{tab!=='coverage'&&<select aria-label="자원 유형" value={type} onChange={e=>selectFilter(setType,e.target.value)}><option value="">전체 자원 유형</option>{options('type').map(v=><option key={v}>{v}</option>)}</select>}</div>
        {tab==='resources' && <>
          <div className="inv-services"><button className={!service?'on':''} onClick={()=>{setService('');setType('');setPage(0)}}>전체 ({n(snapshot.resources.length)})</button>{[...new Map(snapshot.resources.map(r=>[r.service,r.group])).entries()].sort((a,b)=>a[1]-b[1]).map(([name])=><button key={name} className={service===name?'on':''} onClick={()=>{setService(name);setType('');setPage(0)}}>{name} ({n(snapshot.summary.by_service[name]??0)})</button>)}</div>
          <div className="inv-table-tools"><span>{n(filtered.length)}개 자원</span><label><input type="checkbox" checked={ids} onChange={e=>setIds(e.target.checked)}/> OCID 열 표시</label></div>
          {!filtered.length && <div className="inv-no-results">조건에 맞는 자원이 없습니다.</div>}
          {[...groups.entries()].map(([comp,rows])=><section className="inv-group" key={comp}><h3>{comp} <span>({n(filtered.filter(r=>r.compartment===comp).length)})</span></h3><div className="inv-table-scroll"><table><thead><tr><th>리전 / 유형</th><th>자원 이름</th><th>상태</th>{fields.length?fields.map(([p,label])=><th key={p}>{label}</th>):<th>핵심 설정</th>}<th>확인</th>{ids && <><th>OCID</th><th>부모 OCID</th></>}<th>Raw JSON</th></tr></thead><tbody>{rows.map(r=><tr key={r.key} className={r.freshness==='stale'?'stale':''}><td><small>{r.region}</small>{r.type}</td><td><button className="inv-resource-link" onClick={()=>setDetail(r)}>{r.name}</button></td><td><span className="inv-state">{r.state||'—'}</span>{r.freshness==='stale' && <small>이전 수집 정보</small>}</td>{fields.length?fields.map(([p])=><td key={p}><div className="inv-cell">{compactValue(r.properties.find(x=>x.field===p)?.value)}</div></td>):<td><div className="inv-property-preview">{r.properties.slice(0,3).map(p=><div key={p.field}><span>{p.label}</span><b>{compactValue(p.value)}</b></div>)}</div><button className="inv-text-button" onClick={()=>setDetail(r)}>설정 {r.properties.length}개 보기</button></td>}<td>{findings.some(f=>f.resource_key===r.key)&&<span className="inv-flag">설정 확인</span>}{!r.detail_complete&&<small>상세 미완료</small>}</td>{ids&&<><td className="inv-id">{r.ocid}</td><td className="inv-id">{r.parent_id||'—'}</td></>}<td><button onClick={()=>setDetail(r)}>원문</button></td></tr>)}</tbody></table></div></section>)}
          <div className="inv-pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>이전</button><span>{page+1} / {Math.max(1,Math.ceil(filtered.length/50))}</span><button disabled={(page+1)*50>=filtered.length} onClick={()=>setPage(p=>p+1)}>다음</button></div>
        </>}
        {tab==='changes' && <div className="inv-change-list">{!snapshot.comparison_run_id && <div className="inv-no-results">첫 수집은 비교 기준으로 보관합니다. 다음 수집부터 변경 내역이 표시됩니다.</div>}{snapshot.changes.filter(c=>(!compartment||c.compartment===compartment)&&(!region||c.region===region)&&(!type||c.type===type)&&(!service||keys.has(c.key))&&(!query||[c.name,c.type,JSON.stringify(c.fields)].join(' ').toLowerCase().includes(query.toLowerCase()))).map((c,i)=><article key={c.key+i}><div className="inv-change-heading"><span className={'inv-change-kind '+c.kind}>{changeLabel[c.kind]??c.kind}</span><button className="inv-resource-link" onClick={()=>navigateResource(c.key)}>{c.name}</button><small>{c.compartment} · {c.type}</small></div>{c.kind==='MISSING'&&<p>정상 완료된 조회 범위에서 사라졌습니다. 실제 삭제인지 다른 범위로 이동했는지 확인이 필요합니다.</p>}{c.fields.map((f,j)=><div className="inv-diff" key={f.path+j}><code>{f.path}</code><div><small>이전</small><pre>{formatValue(f.before)}</pre></div><div><small>현재</small><pre>{formatValue(f.after)}</pre></div></div>)}</article>)}{snapshot.comparison_run_id&&!snapshot.changes.length&&<div className="inv-no-results">비교 가능한 자원에서 변경이 발견되지 않았습니다.</div>}</div>}
        {tab==='findings' && <div className="inv-findings"><p className="inv-muted">기본값과 다른 설정이 모두 문제인 것은 아닙니다. 유형과 근거를 함께 확인하세요.{customRules&&' 현재 브라우저의 수정된 기준을 적용했습니다.'}</p>{findings.filter(f=>keys.has(f.resource_key)).map((f,i)=><article key={f.resource_key+f.rule_id+i}><div><span className="inv-flag">{{nondefault:'기본값 차이',configuration:'설계 특성',review:'운영 검토'}[f.category]??f.category}</span><h3>{f.title}</h3><button className="inv-resource-link" onClick={()=>navigateResource(f.resource_key)}>{f.resource_name}</button><small>{f.compartment} · {f.region}</small></div><p>{f.basis}</p><details><summary>설정값 확인</summary><pre>{formatValue(f.actual)}</pre>{f.expected!==undefined&&<><small>비교 기준</small><pre>{formatValue(f.expected)}</pre></>}</details>{f.source_url?.startsWith('https://docs.oracle.com/')&&<a href={f.source_url} target="_blank" rel="noreferrer">Oracle 기준 문서 ↗</a>}</article>)}</div>}
        {tab==='coverage' && <div className="inv-coverage"><p className="inv-muted">등록된 수집기 기준입니다. OCI 전체 서비스의 자원 부재를 보장하지 않습니다. 미지원 유형도 Search에서 발견한 정보는 보존합니다.</p><div className="inv-table-tools"><span>{n(coverageRows.length)}개 조회</span><label><input type="checkbox" checked={onlyIssues} onChange={e=>{setOnlyIssues(e.target.checked);setCoverageLimit(100)}}/> 확인 필요한 조회만</label></div>{!coverageRows.length&&<div className="inv-no-results">선택한 조건에서 확인할 조회가 없습니다.</div>}<div className="inv-table-scroll"><table><thead><tr><th>조회 작업</th><th>결과</th><th>리전</th><th>자원 수</th><th>설명 / 범위</th></tr></thead><tbody>{coverageRows.slice(0,coverageLimit).map((c,i)=><tr key={c.scope+i}><td>{c.operation}</td><td><span className={!good.has(c.status)?'inv-flag':''}>{c.status}</span></td><td>{c.region||'—'}</td><td>{c.count??'—'}</td><td><div className="inv-cell">{c.error||c.reason||c.scope}</div></td></tr>)}</tbody></table></div>{coverageRows.length>coverageLimit&&<button onClick={()=>setCoverageLimit(v=>v+100)}>다음 100개 보기</button>}</div>}
        <footer className="inv-footer"><span>{date(snapshot.started_at)} 수집 · 원본 상세는 오른쪽 패널에서 확인</span><button onClick={()=>downloadJson(snapshot,`${snapshot.tenancy.name}_${snapshot.run_id}.json`)}>JSON 백업</button><button onClick={()=>perform(async()=>{if(!window.confirm('현재 수집 이력을 이 브라우저에서 제거할까요? 원본 JSON 파일은 삭제되지 않습니다.'))return;await removeSnapshot(selected);const rows=await refresh();setSelected(rows[0]?.id??'');if(!rows.length)setSnapshot(undefined)})}>브라우저에서 제거</button></footer>
      </>}</main>
    </div>}
    <input hidden ref={file} type="file" accept=".json,application/json" multiple onChange={e=>void importFiles(e.target.files)}/>
    {detail && <div className="inv-drawer-backdrop" onClick={()=>setDetail(undefined)}><aside className="inv-drawer" aria-label="자원 상세" onClick={e=>e.stopPropagation()}><div className="inv-drawer-head"><div><small>{detail.service} / {detail.type}</small><h2>{detail.name}</h2></div><button aria-label="상세 닫기" onClick={()=>setDetail(undefined)}>닫기</button></div><p>{detail.compartment} · {detail.region}</p><p className="inv-muted">상세 확인: {detail.detail_observed_at?date(detail.detail_observed_at):'미완료'} · {detail.freshness==='cached'?'보존된 상세 재사용':detail.freshness==='stale'?'이전 수집 정보':'현재 수집'}</p><InventoryRules resource={detail} resources={snapshot?.resources??[]}/><dl className="inv-details">{detail.properties.map(p=><div key={p.field}><dt>{p.label}<code>{p.field}</code></dt><dd><pre>{formatValue(p.value)}</pre></dd></div>)}</dl><h3>연결된 자원 ({detail.relations.length})</h3>{detail.relations.map((r,i)=><div className="inv-relation" key={r.field+r.target+i}><small>{r.field}</small><button onClick={()=>navigateResource(r.target_key??r.target)}>{snapshot?.resources.find(x=>x.ocid===r.target)?.name??r.target}</button></div>)}{detail.previous_detail&&<details className="inv-alert"><summary>이전 정상 수집 상세 보기 ({date(detail.previous_detail.observed_at)})</summary><p>이번 상세 조회가 미완료되어 마지막으로 확인한 설정을 별도 보존했습니다. 현재 설정으로 단정하지 마세요.</p><pre className="inv-raw">{JSON.stringify(detail.previous_detail.raw,null,2)}</pre></details>}<details><summary>OCID · 태그 · Raw JSON</summary><dl className="inv-details"><div><dt>OCID</dt><dd className="inv-id">{detail.ocid}</dd></div><div><dt>부모 OCID</dt><dd className="inv-id">{detail.parent_id||'—'}</dd></div></dl><button onClick={()=>downloadJson(detail.raw,`${detail.type}_raw.json`)}>Raw JSON 저장</button><pre className="inv-raw">{JSON.stringify(detail.raw,null,2)}</pre></details></aside></div>}
    {importOpen&&<div className="inv-modal-backdrop"><section className="inv-modal" role="dialog" aria-modal="true" aria-label="JSON 가져오기"><div className="inv-drawer-head"><h2>수집 데이터 가져오기</h2><button onClick={()=>setImportOpen(false)}>닫기</button></div>{error&&<div className="inv-alert error" role="alert">{error}</div>}<p>실제 OCID·메일·태그를 포함한 데이터를 브라우저 내부에 보관합니다. 공개 사이트로 업로드하지 않습니다.</p><button className="inv-primary" disabled={busy} onClick={()=>file.current?.click()}>JSON 파일 선택</button><details><summary>JSON 붙여넣기</summary><textarea aria-label="수집 JSON" value={jsonText} onChange={e=>setJsonText(e.target.value)} placeholder="{ ... }"/><button disabled={busy||!jsonText} onClick={()=>perform(async()=>importValue(JSON.parse(jsonText)))}>붙여넣은 JSON 가져오기</button></details><details><summary>Postman · 로컬 연결</summary><p>PC에서 bridge.py를 실행하고 Postman으로 JSON을 넣은 뒤 가져올 수 있습니다. 연결 주소는 127.0.0.1:8766으로 고정됩니다.</p><input aria-label="로컬 연결 토큰" type="password" value={bridgeToken} onChange={e=>setBridgeToken(e.target.value)} placeholder="로컬 bridge 토큰"/><button disabled={busy||!bridgeToken} onClick={()=>perform(async()=>{const r=await fetch('http://127.0.0.1:8766/imports',{headers:{Authorization:`Bearer ${bridgeToken}`}});if(!r.ok)throw Error(`로컬 연결 실패 (${r.status}). 파일 가져오기도 사용할 수 있습니다.`);setBridgeFiles(await r.json())})}>로컬 파일 조회</button>{bridgeFiles.map(f=><button className="inv-bridge-file" key={f.id} onClick={()=>perform(async()=>{const r=await fetch(`http://127.0.0.1:8766/imports/${encodeURIComponent(f.id)}`,{headers:{Authorization:`Bearer ${bridgeToken}`}});if(!r.ok)throw Error('로컬 JSON을 읽지 못했습니다.');await importValue(await r.json())})}>{f.tenancy} · {date(f.at)}</button>)}</details></section></div>}
    {rulesOpen&&<div className="inv-modal-backdrop"><section className="inv-modal wide" role="dialog" aria-modal="true" aria-label="기준 관리"><div className="inv-drawer-head"><h2>설정 비교 기준</h2><button onClick={()=>setRulesOpen(false)}>닫기</button></div>{error&&<div className="inv-alert error" role="alert">{error}</div>}<p>규칙의 기준값, 대상 자원, 표시 이유를 수정합니다. 적용 결과는 이 브라우저에 저장됩니다. 매일 수집에도 적용하려면 내보낸 JSON으로 수집기의 baselines.json을 갱신하세요.</p><textarea aria-label="기준 규칙 JSON" spellCheck={false} value={rulesText} onChange={e=>setRulesText(e.target.value)}/><div className="inv-actions"><button onClick={()=>perform(async()=>{const rules=validateRules(JSON.parse(rulesText));downloadJson(rules,'baselines.json')})}>규칙 JSON 내보내기</button><button className="inv-primary" onClick={()=>perform(async()=>{const rules=validateRules(JSON.parse(rulesText));await saveRules(rules);setCustomRules(rules);setRulesOpen(false);setTab('findings');setMessage('수정한 기준을 적용했습니다.')})}>검증 후 적용</button></div></section></div>}
  </section>
}
