import fs from 'node:fs/promises';
import path from 'node:path';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const [runtimeModules,input,output]=process.argv.slice(2);
const require=createRequire(path.join(runtimeModules,'package.json'));
const {chromium}=require('playwright');
await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'});
const context=await browser.newContext({viewport:{width:1520,height:1050}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/#/knowledge/inventory');
await page.locator('.ksec-btn').filter({hasText:'리소스 현행화'}).waitFor();
assert.equal(await page.getByRole('button',{name:'JSON 가져오기',exact:true}).count(),0,'Locked route must not mount the inventory component');
await page.screenshot({path:path.join(output,'01-locked.png')});
await page.goto('http://127.0.0.1:5173/_inventory_qa.html');
await page.getByRole('heading',{name:'리소스 현행화',exact:true}).waitFor();
await page.locator('input[type=file]').setInputFiles(input);
await page.getByRole('tab',{name:'자원 탐색',exact:true}).waitFor();
await page.getByLabel('자원 유형',{exact:true}).selectOption('Instance');
await page.screenshot({path:path.join(output,'02-resources.png'),fullPage:true});
const rows=page.locator('tbody tr');assert.ok(await rows.count()>0);
await rows.first().getByRole('button',{name:'원문',exact:true}).click();
await page.getByLabel('자원 상세',{exact:true}).waitFor();
await page.getByText('OCID · 태그 · Raw JSON',{exact:true}).click();
assert.ok((await page.locator('.inv-raw').textContent()).includes('shape'));
await page.screenshot({path:path.join(output,'03-detail.png')});
await page.getByLabel('상세 닫기').click();
await page.getByRole('tab',{name:'설정 확인',exact:true}).click();
await page.getByLabel('자원 유형',{exact:true}).selectOption('');
await page.screenshot({path:path.join(output,'04-findings.png'),fullPage:true});
await page.getByRole('button',{name:'기준 관리',exact:true}).click();
assert.ok((await page.getByLabel('기준 규칙 JSON').inputValue()).includes('bucket-public'));
await page.getByRole('dialog',{name:'기준 관리'}).getByRole('button',{name:'닫기',exact:true}).click();
await page.reload();await page.getByRole('tab',{name:'자원 탐색',exact:true}).waitFor();
assert.ok(await page.locator('.inv-customers button').count()>0,'IndexedDB data survives reload');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'05-mobile.png'),fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1),false,'No mobile document overflow');
await page.setViewportSize({width:1520,height:1050});
await page.getByLabel('자원 검색',{exact:true}).fill('no-resource-matches-this');
await page.getByText('조건에 맞는 자원이 없습니다.',{exact:true}).waitFor();
await page.getByLabel('자원 검색',{exact:true}).fill('');
await page.getByRole('tab',{name:'수집 범위',exact:true}).click();
assert.ok(await page.getByText('UNVERIFIED_LEGACY',{exact:true}).count()>0);
assert.deepEqual(errors,[]);
console.log(JSON.stringify({passed:true,checks:['locked-route','json-import','type-filter','resource-detail','raw-json','findings','rule-editor','indexeddb-reload','mobile-width','empty-filter','coverage'],screenshots:output}));
await browser.close();
